// This file is generated by Firebase Extensions.
'use server';
/**
 * @fileOverview An AI agent that suggests improvements to a student's prompt based on an evaluation rubric.
 *
 * - suggestPromptImprovements - A function that handles the prompt improvement suggestion process.
 * - SuggestPromptImprovementsInput - The input type for the suggestPromptImprovements function.
 * - SuggestPromptImprovementsOutput - The return type for the suggestPromptImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { auth } from '@/server/auth';
import { privacy } from '@/server/privacy';
import { isResearchSession } from '@/lib/research/session-modes';
import type { SessionType } from '@/lib/research/types';

const SuggestPromptImprovementsInputSchema = z.object({
  studentPrompt: z
    .string()
    .describe('The prompt submitted by the student.'),
  rubric: z.string().describe('The evaluation rubric to use.'),
  samplePrompt: z.string().optional().describe('A sample correct prompt.'),
  photoDataUri: z
    .string()
    .describe(
      "A photo for which the prompt is intended to describe, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type SuggestPromptImprovementsInput = z.infer<typeof SuggestPromptImprovementsInputSchema>;

const SuggestPromptImprovementsOutputSchema = z.object({
  improvements: z.string().describe('Specific suggestions for improving the prompt.'),
  score: z.number().describe('The score of the prompt based on the rubric.'),
});
export type SuggestPromptImprovementsOutput = z.infer<typeof SuggestPromptImprovementsOutputSchema>;

/**
 * 제안 생성은 승인된 작업으로만 쓴다. 연구 세션에서는 임의 호출을 막는다.
 * 화면에서 버튼을 숨기는 것으로 차단을 대신하지 않고 이 서버 액션이 직접 거부한다.
 *
 * 학생 입력은 평가 대상 데이터이지 채점 지시가 아니다. 개인정보 의심 내용은
 * 외부 전송을 멈추고 교사 확인을 받는다.
 */
export async function suggestPromptImprovements(input: SuggestPromptImprovementsInput): Promise<SuggestPromptImprovementsOutput> {
  const session = await auth.resolveSessionContext().catch(() => null);
  if (session && isResearchSession(session.sessionType as SessionType)) {
    throw new Error('지금은 선생님이 연 활동만 할 수 있어요.');
  }

  const check = privacy.checkBeforeSend(input.studentPrompt);
  if (check.decision === 'hold_for_teacher') {
    // 탐지된 유형만 남긴다. 원문 조각을 오류 메시지·로그에 넣지 않는다.
    throw new Error(check.notice);
  }

  return suggestPromptImprovementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPromptImprovementsPrompt',
  input: {schema: SuggestPromptImprovementsInputSchema},
  output: {schema: SuggestPromptImprovementsOutputSchema},
  prompt: `당신은 친절한 AI 선생님입니다. 한국의 초등학생들이 프롬프트 엔지니어링 기술을 배우는 것을 돕고 있습니다.

제공된 루브릭을 바탕으로 학생의 프롬프트를 평가해 주세요. 점수는 100점 만점에 가급적 70점 이상으로 후하게 주고, 칭찬을 많이 해주세요. 
피드백은 초등학생이 이해하기 쉽게, 친절하고 격려하는 말투로 작성해 주세요.

모든 결과물은 한국어로 작성되어야 합니다.

평가 루브릭:
{{rubric}}

학생의 프롬프트:
{{studentPrompt}}

{% if samplePrompt %}
참고용 샘플 정답 프롬프트입니다. 제안에 샘플 프롬프트의 요소를 통합할 수 있습니다.
{{samplePrompt}}
{% endif %}

사진:
{{media url=photoDataUri}}
`,
});

const suggestPromptImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestPromptImprovementsFlow',
    inputSchema: SuggestPromptImprovementsInputSchema,
    outputSchema: SuggestPromptImprovementsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
